### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by danylo-svietashov** [oleksandrblazhko/nai205-svetashov#4]
**Завдання 1**
Потреба: Створення живопису
Доступність: завдяки тому, що ПП дозволяє переглядати, вибирати та замовлювати потрібні витратні матеріали для створення живопису, потреба є доступною.
Зрозумілість: для того щоб створити живопис існує подробна інструкція з цього процесу, користувач може переглядати цю інструкцію та розуміти всі важливі етапи цього процесу.
Цінність: потреба є корисною, але для її задоволення не потрібно нічого платити.

**Comment by daniil-svetashov** [comment]
Завдання 2
Перший прецедент надає користувачу можливість зареєструватися, тим самим наближає користувача до досягнення мети програмного продукту пов’язаної з безпекою праці.
Другий прецедент надає можливість замовляти фарби, тим самим наближує його до досягнення мети програмного продукту пов’язаної зі створенням живопису.
Третій прецедент надає можливість формувати вимоги до освітлення, тим самим наближує користувача до досягнення мети програмного продкуту пов’язаної з освітленням навколишнього середовища.

**Comment by daniil-svetashov** [comment]
Завдання 2
Перший прецедент надає користувачу можливість зареєструватися, тим самим наближає користувача до досягнення мети програмного продукту пов’язаної з безпекою праці.
Другий прецедент надає можливість замовляти фарби, тим самим наближує його до досягнення мети програмного продукту пов’язаної зі створенням живопису.
Третій прецедент надає можливість формувати вимоги до освітлення, тим самим наближує користувача до досягнення мети програмного продкуту пов’язаної з освітленням навколишнього середовища.

**Comment by danylo-svietashov** [comment]
**Завдання 2**
Перший прецедент надає користувачу можливість зареєструватися, тим самим наближає користувача до досягнення мети програмного продукту пов’язаної з безпекою праці.
Другий прецедент надає можливість користувачу замовляти фарби, тим самим наближує його до досягнення мети програмного продукту пов’язаної зі створенням живопису.
Третій прецедент надає можливість формувати вимоги до освітлення, тим самим наближує користувача до досягнення мети програмного продкуту пов’язаної з освітленням навколишнього середовища.

**Comment by oleksandrblazhko** [comment]
Оцінка  =3 бали
