### ISSUE TITLE
СW2

### ISSUE THREAD

**Issue by danylo-svietashov** [oleksandrblazhko/nai205-svetashov#7]
Завдання 1:
1. Художник переглядає товари та замовлює їх
2. Художник додає
3. Художник сплачує заказ за допомогою кнопки “Сплатити”

**Comment by danylo-svietashov** [comment]
Завдання 2:

1. Показник “Розподіленя система” -  має значення 3. Мій ПП має середню навантаженність різними функціями та процесами. Лише дії, які можуть виконати користувачі з певними даними, або офісні работники з інформацією бази даних.
2. Показник “Спеціальні вимоги до навчання користувачів - має значення 2 ”. Мій ПП вимагає від кожного типу користуачів певні навички у створенні живопису, але вони не великі. Також ПП не вимагає від користувача наявність певного рівня освіти.

**Comment by oleksandrblazhko** [comment]
3 бали
